export const JWTStorage = {
    JWT_TOKEN:'JWT_TOKEN'
}

export const DefStorage = {
    DEF_ACTIVITIES:'DEF_ACTIVITIES',
    DEF_ACTIVITY_CATEGORIES:'DEF_ACTIVITY_CATEGORIES',
    DEF_SETUP_QUESTIONS:'DEF_SETUP_QUESTIONS'
}

export const UserStorage = {
    CURRENT_USER:'CURRENT_USER',
}

export const FamilyStorage = {
    DEF_FAMILY_MEMBER_TYPES:'DEF_FAMILY_MEMBER_TYPES'
}

export const ProjectStorage = {
    CURRENT_PROJECT:'CURRENT_PROJECT',
    CURRENT_PROJECT_USER:'CURRENT_PROJECT_USER'
}

export const AppStorage = {
    CURRENT_APP_VERSION:'CURRENT_APP_VERSION'
}